import { Inter } from "next/font/google";

import "@src/globals.css";

import type { Metadata } from "next";
import type { FC, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

type RootLayoutComponent = FC<{
  children: ReactNode;
}>;
const RootLayout: RootLayoutComponent = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
