const INITIAL_START_TIME = new Date(1420070400000); // January 1st 2015

const MONTHS_PER_YEAR = 12;
const DAYS_PER_YEAR = 365;
const HOURS_PER_DAY = 24;
const MINUTES_PER_HOUR = 60;
const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_SECOND = 1000;

export {
  DAYS_PER_YEAR,
  HOURS_PER_DAY,
  INITIAL_START_TIME,
  MILLISECONDS_PER_SECOND,
  MINUTES_PER_HOUR,
  MONTHS_PER_YEAR,
  SECONDS_PER_MINUTE,
};
